file1 = open("30_days_30_hours_operation.txt","w+")
file1.write("I have completed 10 days successfully \n")
file1.close()
file1 = open("30_days_30_hours_operation.txt","a")
file1.write("AKSHAYA A.P")
file1.close()
file1 = open("30_days_30_hours_operation.txt","r+")
print(file1.read())
file1.close()
